name: 'Configure node js and its cache'
description: 'Configure node js and its cache'
runs:
  using: "composite"
  steps:
  - name: "Setup node"
    uses: actions/setup-node@v3
    with:
      node-version: ${{ env.NODE_VERSION }}

  - name: "Node Cache"
    id: node-cache
    uses: actions/cache@v3.0.2  # This action allows caching dependencies and build outputs to improve workflow execution time.
    with:
      path: '**/node_modules'
      key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

  - name: "Build node cache [OPTIONAL]"
    if: steps.node-cache.outputs.cache-hit != 'true'
    shell: bash
    run: npm ci && npm run clean && npm run compile
