name: 'Solidity grouped unit tests'
description: 'Runs the solidity unit tests in groups'

inputs:
  test-group:
    description: 'Regex to math the folder inside the test folder'
    required: true
  sub-filter-include:
    description: 'Sub folder to include in the search'
    required: false
  sub-filter-exclude:
    description: 'Sub folder to exclude in the search'
    required: false

runs:
  using: "composite"    # It contains a list of steps to run as opposed to a program to execute
  steps:
      # It is called right after /node-cache actions. I don't think this step is necessary. To Be Verified
        #  - shell: bash
        #    working-directory: ./bridge
        #    run: npm run clean && npm run compile
  - name: "Solidity test"
    shell: bash
    working-directory: ./bridge
    run: |
      SUB_FILTER_INCLUDE=/${{ inputs.sub-filter-include }}
      # if inputs.sub-filter-include is empty we have to remove '/' otherwise the find command bellow will fail
      if [[ "$SUB_FILTER_INCLUDE" == "/" ]];  then
        SUB_FILTER_INCLUDE=""
      fi
      ls ./test | \
      grep "^${{ inputs.test-group }}" | \
      xargs -n 1 -I {} echo ./test/{}$SUB_FILTER_INCLUDE | \
      xargs -n 1 -I {} find -P {} -type f -iname '*.ts' -not -path "*/${{ inputs.sub-filter-exclude }}/*" | \
      xargs npm run test-parallel --
